version: '3.8'   
services:  
    auth-postgres:
      container_name: auth-postgres
      hostname: auth-postgres
      image: postgres
      ports:
        - "5432:5432"
      restart: unless-stopped
      env_file:
        - dbcredentials.env
      volumes:
        - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
        - ./db_data/data/volumes/myproject/auth-postgres:/var/lib/postgresql/data/
      networks:
        - hex-arch-net

    firestore:
      image: firestore
      build:
        context: ./firestore_utils/
        dockerfile: Dockerfile.Firestore
      ports:
        - 4000:4000
        - 8200:8200
        - 8085:8085
        - 5001:5001
        - 5005:5005
      environment:
        - FIRESTORE_PORT=8200
        - FIRESTORE_EMULATOR_HOST="localhost:8200"
        - PUBSUB_EMULATOR_HOST="localhost:8085"
        - GCLOUD-PROJECT-NAME="dummy-project"
      volumes:
        - ./db_data/firestore_data:/firestore/exported-dev-data
        - ./db_data/firestore_data/firestore.indexes.json:/firebase/firestore.indexes.json
        - ./firestore_utils/firestore.rules:/firebase.rules
        - ./firestore_utils/functions:/firebase/functions
      networks:
        - hex-arch-net

  
    couchserver:
      image: couchdb
      restart: always
      ports:
        - "5984:5984"
      environment:
        - COUCHDB_USER=oscardockercouchdb
        - COUCHDB_PASSWORD=oscarcouchpass
      volumes:
          - ./db_data/dbdata:/opt/couchdb/data
      networks:
        - hex-arch-net

networks:
  hex-arch-net:
    driver: bridge